/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;

/**
 *
 * @author u06769532123
 */
public class JFrmTeste extends javax.swing.JFrame {

    /**
     * Creates new form java
     */
    public JFrmTeste() {
        initComponents();
        jBtnAbilitar.setEnabled(false);
        jBtnvisivel.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblNome = new javax.swing.JLabel();
        jTxtNome = new javax.swing.JTextField();
        jLblTipo = new javax.swing.JLabel();
        jCboTipo = new javax.swing.JComboBox<>();
        jBtnDesabilitar = new javax.swing.JButton();
        jBtnAbilitar = new javax.swing.JButton();
        jBtnInvisivel = new javax.swing.JButton();
        jBtnvisivel = new javax.swing.JButton();
        jBtnok = new javax.swing.JButton();
        jBtnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLblNome.setText("Nome");

        jTxtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtNomeFocusLost(evt);
            }
        });

        jLblTipo.setText("Tipo");

        jCboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCboTipo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jCboTipoFocusLost(evt);
            }
        });

        jBtnDesabilitar.setText("Desabilitar");
        jBtnDesabilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDesabilitarActionPerformed(evt);
            }
        });

        jBtnAbilitar.setText("Abilitar");
        jBtnAbilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAbilitarActionPerformed(evt);
            }
        });

        jBtnInvisivel.setText("Invisível");
        jBtnInvisivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnInvisivelActionPerformed(evt);
            }
        });

        jBtnvisivel.setText("Visivel");
        jBtnvisivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnvisivelActionPerformed(evt);
            }
        });

        jBtnok.setText("Sumir tudo");
        jBtnok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnokActionPerformed(evt);
            }
        });

        jBtnLimpar.setText("Limpar");
        jBtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTxtNome)
                        .addComponent(jCboTipo, javax.swing.GroupLayout.Alignment.TRAILING, 0, 190, Short.MAX_VALUE)
                        .addComponent(jLblNome)
                        .addComponent(jLblTipo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnok)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnLimpar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnDesabilitar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnAbilitar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnInvisivel)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnvisivel)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnDesabilitar)
                    .addComponent(jBtnAbilitar)
                    .addComponent(jBtnvisivel)
                    .addComponent(jBtnInvisivel))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnok)
                    .addComponent(jBtnLimpar))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnDesabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDesabilitarActionPerformed
        // TODO add your handling code here:
        jTxtNome.setEnabled(false);
        jCboTipo.setEnabled(false);
        jBtnDesabilitar.setEnabled(false);
        jBtnAbilitar.setEnabled(true);
        jLblNome.setEnabled(false);
        jLblTipo.setEnabled(false);
    }//GEN-LAST:event_jBtnDesabilitarActionPerformed

    private void jBtnAbilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAbilitarActionPerformed
        // TODO add your handling code here:
        jTxtNome.setEnabled(true);
        jCboTipo.setEnabled(true);
        jBtnDesabilitar.setEnabled(true);
        jBtnAbilitar.setEnabled(false);
        jLblNome.setEnabled(true);
        jLblTipo.setEnabled(true);
    }//GEN-LAST:event_jBtnAbilitarActionPerformed

    private void jBtnvisivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnvisivelActionPerformed
        // TODO add your handling code here:
        jLblNome.setVisible(true);
        jTxtNome.setVisible(true);
        jLblTipo.setVisible(true);
        jCboTipo.setVisible(true);
        jBtnAbilitar.setVisible(true);
        jBtnDesabilitar.setVisible(true);
        jBtnvisivel.setEnabled(false);
        jBtnInvisivel.setEnabled(true);
    }//GEN-LAST:event_jBtnvisivelActionPerformed

    private void jBtnInvisivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnInvisivelActionPerformed
        // TODO add your handling code here:
        jLblNome.setVisible(false);
        jTxtNome.setVisible(false);
        jLblTipo.setVisible(false);
        jCboTipo.setVisible(false);
        jBtnAbilitar.setVisible(false);
        jBtnDesabilitar.setVisible(false);
        jBtnvisivel.setEnabled(true);
        jBtnInvisivel.setEnabled(false);
    }//GEN-LAST:event_jBtnInvisivelActionPerformed

    private void jBtnokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnokActionPerformed
        // TODO add your handling code here:
        
        boolean estado = jCboTipo.isVisible();
        jLblNome.setVisible(!estado);
        jLblTipo.setVisible(!estado);
        jTxtNome.setVisible(!estado);
        jCboTipo.setVisible(!estado);
        jBtnAbilitar.setVisible(!estado);
        jBtnDesabilitar.setVisible(!estado);
        jBtnvisivel.setVisible(!estado);
        jBtnInvisivel.setVisible(!estado);
    }//GEN-LAST:event_jBtnokActionPerformed

    private void jBtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLimparActionPerformed
        // TODO add your handling code here:
        jTxtNome.setText("");
    }//GEN-LAST:event_jBtnLimparActionPerformed

    private void jTxtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtNomeFocusLost
        // TODO add your handling code here:
        jTxtNome.setBackground(Color.white);
    }//GEN-LAST:event_jTxtNomeFocusLost

    private void jCboTipoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jCboTipoFocusLost
        // TODO add your handling code here:
        jTxtNome.setBackground(Color.WHITE);
    }//GEN-LAST:event_jCboTipoFocusLost

    private void jTxtNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtNomeFocusGained
        // TODO add your handling code here:
        jTxtNome.setBackground(Color.gray);
    }//GEN-LAST:event_jTxtNomeFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmTeste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAbilitar;
    private javax.swing.JButton jBtnDesabilitar;
    private javax.swing.JButton jBtnInvisivel;
    private javax.swing.JButton jBtnLimpar;
    private javax.swing.JButton jBtnok;
    private javax.swing.JButton jBtnvisivel;
    private javax.swing.JComboBox<String> jCboTipo;
    private javax.swing.JLabel jLblNome;
    private javax.swing.JLabel jLblTipo;
    private javax.swing.JTextField jTxtNome;
    // End of variables declaration//GEN-END:variables
}
